/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab01;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
