/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab01;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        Student s1 = new Student("12345678", "Zac Seales");
        
        System.out.println(s1.toString());
    }
}
